# Generated by Django 5.0.6 on 2024-06-04 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='actualite')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
